seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

firefoxnode:
  image: selenium/node-firefox
  ports:
    - 5901
  links:
    - seleniumhub:hub

chromenode:
  image: selenium/node-chrome
  ports:
    - 5901
  links:
    - seleniumhub:hub

chromestandalone:
  image: yegor256/java-maven
  links:
   - seleniumhub:localhost
  volumes:
   - .:/home
  command: bash -c "cd home && mvn clean test -DsuiteXmlFile=testng.xml"

