seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

firefoxnode:
  image: selenium/node-firefox
  ports:
    - 5900
  links:
    - seleniumhub:hub

chromenode:
  image: selenium/node-chrome
  ports:
    - 5900
  links:
    - seleniumhub:hub

chromestandalone:
  image: deathbypython/chrome-selenium-awesome:latest
  ports:
   - 4444:4444
  volumes:
   - .:/home
  command: bash -c "mvn clean test -DsuiteXmlFile=testng.xml"

